
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.enemyLevel
{
public sealed partial class EnemyLevelConfig : Luban.BeanBase
{
    public EnemyLevelConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Desc = _buf.ReadString();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);EmemyWeight = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); EmemyWeight[__index0] = __e0;}}
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);EmemyIds = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); EmemyIds[__index0] = __e0;}}
        InternalTime = _buf.ReadInt();
    }

    public static EnemyLevelConfig DeserializeEnemyLevelConfig(ByteBuf _buf)
    {
        return new enemyLevel.EnemyLevelConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 怪物权重
    /// </summary>
    public readonly int[] EmemyWeight;
    /// <summary>
    /// 怪物id
    /// </summary>
    public readonly int[] EmemyIds;
    /// <summary>
    /// 生成间隔（ms）
    /// </summary>
    public readonly int InternalTime;
   
    public const int __ID__ = -1839868368;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "desc:" + Desc + ","
        + "ememyWeight:" + Luban.StringUtil.CollectionToString(EmemyWeight) + ","
        + "ememyIds:" + Luban.StringUtil.CollectionToString(EmemyIds) + ","
        + "internalTime:" + InternalTime + ","
        + "}";
    }
}

}

