
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.enemyLevel
{
public partial class TbEnemyLevel
{
    private readonly System.Collections.Generic.Dictionary<int, enemyLevel.EnemyLevelConfig> _dataMap;
    private readonly System.Collections.Generic.List<enemyLevel.EnemyLevelConfig> _dataList;
    
    public TbEnemyLevel(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, enemyLevel.EnemyLevelConfig>();
        _dataList = new System.Collections.Generic.List<enemyLevel.EnemyLevelConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            enemyLevel.EnemyLevelConfig _v;
            _v = enemyLevel.EnemyLevelConfig.DeserializeEnemyLevelConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, enemyLevel.EnemyLevelConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<enemyLevel.EnemyLevelConfig> DataList => _dataList;

    public enemyLevel.EnemyLevelConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public enemyLevel.EnemyLevelConfig Get(int key) => _dataMap[key];
    public enemyLevel.EnemyLevelConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

