
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.role
{
public sealed partial class Role : Luban.BeanBase
{
    public Role(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        ResPath = _buf.ReadString();
        Cost = _buf.ReadInt();
        Ai = _buf.ReadInt();
        EmemyAi = _buf.ReadInt();
        MoveSpeed = _buf.ReadFloat();
        MaxHp = _buf.ReadInt();
        BasePhysicalAttack = _buf.ReadInt();
        AttackDistance = _buf.ReadInt();
        DeathTime = _buf.ReadInt();
        NormalSkillId = _buf.ReadInt();
    }

    public static Role DeserializeRole(ByteBuf _buf)
    {
        return new role.Role(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 角色预制
    /// </summary>
    public readonly string ResPath;
    /// <summary>
    /// 花费
    /// </summary>
    public readonly int Cost;
    /// <summary>
    /// aiId
    /// </summary>
    public readonly int Ai;
    /// <summary>
    /// 作为敌人时ai
    /// </summary>
    public readonly int EmemyAi;
    /// <summary>
    /// 移动速度
    /// </summary>
    public readonly float MoveSpeed;
    /// <summary>
    /// 初始最大血量
    /// </summary>
    public readonly int MaxHp;
    /// <summary>
    /// 基础物理攻击
    /// </summary>
    public readonly int BasePhysicalAttack;
    /// <summary>
    /// 攻击距离
    /// </summary>
    public readonly int AttackDistance;
    /// <summary>
    /// 死亡时间（ms）
    /// </summary>
    public readonly int DeathTime;
    /// <summary>
    /// 普攻技能id
    /// </summary>
    public readonly int NormalSkillId;
   
    public const int __ID__ = 289769230;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "resPath:" + ResPath + ","
        + "cost:" + Cost + ","
        + "ai:" + Ai + ","
        + "ememyAi:" + EmemyAi + ","
        + "moveSpeed:" + MoveSpeed + ","
        + "maxHp:" + MaxHp + ","
        + "basePhysicalAttack:" + BasePhysicalAttack + ","
        + "attackDistance:" + AttackDistance + ","
        + "deathTime:" + DeathTime + ","
        + "normalSkillId:" + NormalSkillId + ","
        + "}";
    }
}

}

