
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.role
{
public sealed partial class Role : Luban.BeanBase
{
    public Role(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        Cost = _buf.ReadInt();
        Ai = _buf.ReadInt();
    }

    public static Role DeserializeRole(ByteBuf _buf)
    {
        return new role.Role(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 花费
    /// </summary>
    public readonly int Cost;
    /// <summary>
    /// aiId
    /// </summary>
    public readonly int Ai;
   
    public const int __ID__ = 289769230;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "cost:" + Cost + ","
        + "ai:" + Ai + ","
        + "}";
    }
}
}

