
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.role
{
public partial class TbRole
{
    private readonly System.Collections.Generic.Dictionary<int, role.Role> _dataMap;
    private readonly System.Collections.Generic.List<role.Role> _dataList;
    
    public TbRole(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, role.Role>(n);
        _dataList = new System.Collections.Generic.List<role.Role>(n);
        for(int i = n ; i > 0 ; --i)
        {
            role.Role _v;
            _v = global::GameConfig.role.Role.DeserializeRole(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, role.Role> DataMap => _dataMap;
    public System.Collections.Generic.List<role.Role> DataList => _dataList;

    public role.Role GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public role.Role Get(int key) => _dataMap[key];
    public role.Role this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

