
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.projectile
{
public sealed partial class ProjectileResConfig : Luban.BeanBase
{
    public ProjectileResConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Desc = _buf.ReadString();
        ShootEffect = _buf.ReadString();
        HitEffect = _buf.ReadString();
        ProjectileRes = _buf.ReadString();
    }

    public static ProjectileResConfig DeserializeProjectileResConfig(ByteBuf _buf)
    {
        return new projectile.ProjectileResConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 射击特效
    /// </summary>
    public readonly string ShootEffect;
    /// <summary>
    /// 击中特效
    /// </summary>
    public readonly string HitEffect;
    /// <summary>
    /// 子弹资源
    /// </summary>
    public readonly string ProjectileRes;
   
    public const int __ID__ = -994139020;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "desc:" + Desc + ","
        + "ShootEffect:" + ShootEffect + ","
        + "HitEffect:" + HitEffect + ","
        + "ProjectileRes:" + ProjectileRes + ","
        + "}";
    }
}
}

