
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.projectile
{
public sealed partial class ProjectileConfig : Luban.BeanBase
{
    public ProjectileConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        MoveType = _buf.ReadInt();
        ShootEffect = _buf.ReadString();
        HitEffect = _buf.ReadString();
        ProjectileRes = _buf.ReadString();
        Speed = _buf.ReadFloat();
        Gravity = _buf.ReadFloat();
    }

    public static ProjectileConfig DeserializeProjectileConfig(ByteBuf _buf)
    {
        return new projectile.ProjectileConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 移动类型
    /// </summary>
    public readonly int MoveType;
    /// <summary>
    /// 射击特效
    /// </summary>
    public readonly string ShootEffect;
    /// <summary>
    /// 击中特效
    /// </summary>
    public readonly string HitEffect;
    /// <summary>
    /// 子弹资源
    /// </summary>
    public readonly string ProjectileRes;
    /// <summary>
    /// 子弹速度
    /// </summary>
    public readonly float Speed;
    /// <summary>
    /// 重力
    /// </summary>
    public readonly float Gravity;
   
    public const int __ID__ = -573459440;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "moveType:" + MoveType + ","
        + "ShootEffect:" + ShootEffect + ","
        + "HitEffect:" + HitEffect + ","
        + "ProjectileRes:" + ProjectileRes + ","
        + "Speed:" + Speed + ","
        + "Gravity:" + Gravity + ","
        + "}";
    }
}

}

