
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.projectile
{
public partial class TbProjectileRes
{
    private readonly System.Collections.Generic.Dictionary<int, projectile.ProjectileResConfig> _dataMap;
    private readonly System.Collections.Generic.List<projectile.ProjectileResConfig> _dataList;
    
    public TbProjectileRes(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, projectile.ProjectileResConfig>(n);
        _dataList = new System.Collections.Generic.List<projectile.ProjectileResConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            projectile.ProjectileResConfig _v;
            _v = global::GameConfig.projectile.ProjectileResConfig.DeserializeProjectileResConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, projectile.ProjectileResConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<projectile.ProjectileResConfig> DataList => _dataList;

    public projectile.ProjectileResConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public projectile.ProjectileResConfig Get(int key) => _dataMap[key];
    public projectile.ProjectileResConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

