
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.projectile
{
public partial class TbProjectile
{
    private readonly System.Collections.Generic.Dictionary<int, projectile.ProjectileConfig> _dataMap;
    private readonly System.Collections.Generic.List<projectile.ProjectileConfig> _dataList;
    
    public TbProjectile(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, projectile.ProjectileConfig>();
        _dataList = new System.Collections.Generic.List<projectile.ProjectileConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            projectile.ProjectileConfig _v;
            _v = projectile.ProjectileConfig.DeserializeProjectileConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, projectile.ProjectileConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<projectile.ProjectileConfig> DataList => _dataList;

    public projectile.ProjectileConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public projectile.ProjectileConfig Get(int key) => _dataMap[key];
    public projectile.ProjectileConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

