
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    #region The Tables

    private role.TbRole m_TbRole;
    public role.TbRole TbRole 
    {
        get
        {
            if (m_TbRole == null)
            {
                m_TbRole = new role.TbRole(defaultLoader("role_tbrole"));
                m_TbRole.ResolveRef(this);
            }
            return m_TbRole;
        }
        set
        {
            m_TbRole = value;
            m_TbRole.ResolveRef(this);
        }
    }
    private projectile.TbProjectile m_TbProjectile;
    public projectile.TbProjectile TbProjectile 
    {
        get
        {
            if (m_TbProjectile == null)
            {
                m_TbProjectile = new projectile.TbProjectile(defaultLoader("projectile_tbprojectile"));
                m_TbProjectile.ResolveRef(this);
            }
            return m_TbProjectile;
        }
        set
        {
            m_TbProjectile = value;
            m_TbProjectile.ResolveRef(this);
        }
    }
    private buff.TbBuff m_TbBuff;
    public buff.TbBuff TbBuff 
    {
        get
        {
            if (m_TbBuff == null)
            {
                m_TbBuff = new buff.TbBuff(defaultLoader("buff_tbbuff"));
                m_TbBuff.ResolveRef(this);
            }
            return m_TbBuff;
        }
        set
        {
            m_TbBuff = value;
            m_TbBuff.ResolveRef(this);
        }
    }

    #endregion

    System.Func<string, ByteBuf> defaultLoader;

    public Tables(System.Func<string, ByteBuf> loader)
    {
        SetDefaultLoader(loader);
        Init();
    }
    
    public void SetDefaultLoader(System.Func<string, ByteBuf> loader)
    {
        defaultLoader = null;
        defaultLoader = loader;
    }

    //public partial void Init();

    public void Init(){}
}

}
