
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.buff
{
public sealed partial class BuffConfig : Luban.BeanBase
{
    public BuffConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        ExecuteCount = _buf.ReadInt();
        InternalTime = _buf.ReadFloat();
        Param1 = _buf.ReadString();
    }

    public static BuffConfig DeserializeBuffConfig(ByteBuf _buf)
    {
        return new buff.BuffConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 执行次数
    /// </summary>
    public readonly int ExecuteCount;
    /// <summary>
    /// 执行间隔
    /// </summary>
    public readonly float InternalTime;
    /// <summary>
    /// 参数1
    /// </summary>
    public readonly string Param1;
   
    public const int __ID__ = 683556368;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "executeCount:" + ExecuteCount + ","
        + "internalTime:" + InternalTime + ","
        + "param1:" + Param1 + ","
        + "}";
    }
}

}

