
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.buff
{
public partial class TbBuff
{
    private readonly System.Collections.Generic.Dictionary<int, buff.BuffConfig> _dataMap;
    private readonly System.Collections.Generic.List<buff.BuffConfig> _dataList;
    
    public TbBuff(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, buff.BuffConfig>();
        _dataList = new System.Collections.Generic.List<buff.BuffConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            buff.BuffConfig _v;
            _v = buff.BuffConfig.DeserializeBuffConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, buff.BuffConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<buff.BuffConfig> DataList => _dataList;

    public buff.BuffConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public buff.BuffConfig Get(int key) => _dataMap[key];
    public buff.BuffConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

